isMemoryStorage = false

[postgres]
dsn = "host=postgres port=5432 user=test password=test dbname=calendar sslmode=disable"

[logger]
level = "INFO"

[serverHTTP]
host = ""
port = 8080

[serverGRPC]
host = ""
port = 8081