[postgres]
dsn = "host=postgres port=5432 user=test password=test dbname=calendar sslmode=disable"

[logger]
level = "DEBUG"

[rabbit]
uri = "amqp://guest:guest@rabbitmq:5672/"
exchange = "calendar-ex"
queue = "calendar-q"

[scheduler]
interval = 10