apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
        - name: calendar
          image: zaytcevcom/go-calendar:1.0.1
          ports:
            - containerPort: 8080
            - containerPort: 8081
          command: ["sh", "-c", "sleep 5 && ./opt/app/bin --config configs/calendar/config.toml"]
          volumeMounts:
            - name: config-volume
              mountPath: /configs/calendar
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: calendar-config