version: '3'
services:
  db:
    image: postgres:13
    container_name: calendar_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"