version: '3'
services:
  db:
    image: postgres:13
    container_name: calendar_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calendar_network

  rabbitmq:
    image: rabbitmq:management
    container_name: calendar_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./var/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - calendar_network

networks:
  calendar_network:
    driver: bridge
    external: true