apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
    - name: grpc
      protocol: TCP
      port: {{ .Values.ports.grpc }}
      targetPort: {{ .Values.ports.grpc }}