apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-sender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-sender
  template:
    metadata:
      labels:
        app: calendar-sender
    spec:
      containers:
        - name: calendar-sender
          image: zaytcevcom/go-calendar-sender:1.0.1
          command: ["sh", "-c", "sleep 5 && ./opt/app/bin --config configs/calendar_sender/config.toml"]
          volumeMounts:
            - name: calendar-sender-config
              mountPath: /configs/calendar_sender
      volumes:
        - name: calendar-sender-config
          configMap:
            name: calendar-sender-config